version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: hokage-backend
    env_file:
      - ./backend/.env.prod
    networks:
      - hokage-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: hokage-frontend
    env_file:
      - ./frontend/.env.prod
    ports:
      - "80:80"
    networks:
      - hokage-net

networks:
  hokage-net:
    driver: bridge
